### ISSUE TITLE
Implement parsing and creation of BibXML from iana-registries

### ISSUE THREAD

**Issue by ronaldtse** [ietf-ribose/bibxml-data-iana#2]
We need to parse IANA registry XML data located at https://github.com/ietf-ribose/iana-registries in order to create BibXML entries in this current repository.

**Comment by ronaldtse** [comment]
This is to be done here: https://github.com/relaton/relaton-iana/issues/1

**Comment by andrew2net** [comment]
@ronaldtse 
This file doesn't have `<title>` element: https://github.com/ietf-ribose/iana-registries/blob/main/rpki-signed-objects/rpki-signed-objects.xml
